### ISSUE TITLE
The character metadata endpoint errors out when getting metadata for multiple characters.

### ISSUE THREAD

**Issue by willemm** [eosfrontier/orthanc#25]
https://github.com/eosfrontier/orthanc/blob/8c5ae2b67abc58a68dc7b673464b09544fabbdc3/v2/character/meta/index.php#L6

This line checks the 'id' parameter, which is an optional parameter.  If it's not given, it returns a PHP warning that garbles the json output.

**Comment by WafflesMcDuff** [comment]
I have removed the line that is a duplicate of #26
