### ISSUE TITLE
Request: Unified endpoint for all characters

### ISSUE THREAD

**Issue by SulpherStaer** [eosfrontier/orthanc#26]
During testing, Willem has found that (some parts of) the Player API has a check to see if said ID belongs to a figurant, and will return an error if so.

This behaviour is undesirable, as this would mean apps would need to implement a secondary call on error to the Figuranten API. They both end up speaking to the same database, and as such this is not desirable.

For in game reasons, it is better that most systems are able to see figuranten & players as identical where possible, and only if the app desires, separates figuranten from players.

Similar issue (or even duplicate issue) of https://github.com/eosfrontier/orthanc/issues/25

**Comment by WafflesMcDuff** [comment]
I have changed this to an enhancement as it is currently working as designed and this represents a request for redesign

**Comment by SulpherStaer** [comment]
Understood. Was an explanation given why this was chosen in the discord? I would like to understand the reasoning behind the designed intent. (not criticism, but curiosity & logging in github)
