### ISSUE TITLE
DELETE to completely delete a character from the database

### ISSUE THREAD

**Issue by SulpherStaer** [eosfrontier/orthanc#6]
Orthanc does not have an API that allows deletion of characters. When the figuranten app starts being used, the amount of inactive characters will strongly rise. This can be prevented by allowing deletion.

What I want: 

## Parameters
| Name | Required | Description | Format | Example | Error
|--|--|--|--|--|--
token | yes | provides authentication | uniqueAppKey | JdgU*56437gjk | if not sent
character_id | yes | the id of the character | number | 154 | if not sent or character not found or is not same id of character_name or ICC_number
character_name | yes | the name of the character | string | "swoopsy" | if not sent or name not found or is not same name of character_id or ICC_number
ICC_number | yes | a unique 13 numbered string for ingame identification | 15ch long string in format "1234 12345 1234" | "9787 68768 4365" | if not sent or ICC_number not found or ICC_number is not same number of character_id or character_name

with a positive return message if character is deleted.

The triple identification is required to prevent deletion of the wrong character, people using this API should not auto-fill all fields when deleting. Have the user fill in at least one (most likely name or icc number) to ensure deletion of the proper character.

What I want and what is best practice on handling a delete request might differ greatly.

I understand if the actual API will be different and not have triple confirmation.

**Comment by WafflesMcDuff** [comment]
Went with a different implementation.
We have 2 separate DELETE endpoints. 1 for characters, 1 for figuranten. 
I kept it simple, since the frontend will allow you to select who you're deleting. Sending more than the characterID and your token becomes unnecessary.
